language: cpp

install:
  - sudo apt-get install cmake
  - if ["$BUILD_DOCUMENTATION" == "true"]; then sudo apt-get install cmake doxygen; fi

script: ./script/cibuild

matrix:
  include:
    - compiler: clang
      env: BUILD_DOCUMENTATION=true
    - compiler: gcc
      env: BUILD_DOCUMENTATION=false
